### PR TITLE
Oresim

### PR DESCRIPTION
**Pull request by 19MisterX98**
some people wanted oresim in meteor. (Seed based ore prediction for those who dont know)

I know that the ore gen code that comes with the seed libraries is more accurate but they havent updated to 1.18.
Oresim was originally in Atomic but the client is discontinued now + breaks compatability with meteor.

Those are pretty much the reasons for the port

### CODE REVIEW

**Comment by C10udburst** [comment]
Thanks for the pr

Could you add the module to the README? (if this is a port maybe credit the original source, so the autor doesn't cope in issues about it :trollface:)

**Review by C10udburst — APPROVED** [review]

**Comment by DesiCow** [comment]
@C10udburst @19MisterX98 Does this oresim have baritone integration just like Atomic?

**Comment by C10udburst** [comment]
> Does this oresim have baritone integration just like Atomic?

no

**Comment by DesiCow** [comment]
Hmmm ok

**Pull request merged**
