### PR TITLE
1.20

### PR DESCRIPTION
**Pull request by bluepanee**

### CODE REVIEW

**Comment by yorik100** [comment]
> _ No description provided. _

"All checks have failed
1 failing check"
Might want to check that

**Comment by bluepanee** [comment]
Yep, i already did.

**Review by C10udburst — APPROVED** [review]

**Comment by C10udburst** [comment]
Thanks :pray:

**Comment by Fiz-Vector** [comment]
It took a year to update from 0.2 to 0.3 :shock:

**Pull request merged**
