### PR TITLE
Update to newest dev version - fixes #92

### LINKED ISSUE #92: [Bug] Meteor's way of HUD recently change, likely causes crash on startup
### Describe the bug

Hey so I had downloaded the latest version of the dev build, and the latest version of rejects, and the game crashes at startup.
Looking at the dev logs, it says they (very) recently removed HUD module and moved it to a HUD tab.

The crash log has to do with something involving the HUD, so I assume they are related
Crash log: https://pastebin.com/MTrSRctM

Again this is a very recent change on a dev build, so they might revert back, might not. Just thought I'd post it here just in case

### Steps to reproduce

```plaintext
1. Install both meteor latest dev build & rejects version
2. Launch game
```

### Operating System

Windows

### Rejects Version

b1fa434a9c25d75b2a4b92adb374d8e3f044c673

### Meteor Version

0.4.7-1388

### Minecraft Version

1.18.1

### Other mods

```plaintext
none
```

### PR DESCRIPTION
**Pull request by SIMULATAN**
I had to change up the way the extra config options get registered because that changed too
I hope it's good enough, I'm ready to make edits if necessary

### CODE REVIEW

**Comment by SIMULATAN** [comment]
Bruh that was literally it? lmao

**Comment by C10udburst** [comment]
Thank you for the PR 🙏

when I removed the `ConfigMixin` minecraft started but I got a NPE when opening Config tab:
[crash-2022-01-06_18.36.33-client.txt](https://github.com/AntiCope/meteor-rejects/files/7823723/crash-2022-01-06_18.36.33-client.txt)

**Comment by SIMULATAN** [comment]
Yep, that is because I need to create a instance of the class `ConfigModifier` which adds the options to the config screen

**Comment by SIMULATAN** [comment]
Wait, where did the class go? lol wait i gotta check that, i didn't delete it on purpose

**Comment by SIMULATAN** [comment]
This should've fixed it, somehow messed up the mixin config...

**Comment by C10udburst** [comment]
sorry for the wait, merging

**Comment by SIMULATAN** [comment]
> sorry for the wait, merging

pog

**Pull request merged**
