### PR TITLE
Farm stuff

### PR DESCRIPTION
**Pull request by ThebestkillerTBK**
Farming AIO module

### CODE REVIEW

**Comment by I-Got-You-Dead** [comment]
“we do a little farming” :trollface:

**Review by C10udburst — APPROVED** [review]

**Comment by ThebestkillerTBK** [comment]
> harvest-yeahilif [ harvest-yeahilif ](https://user-images.githubusercontent.com/18114966/211141381-f006182e-fe2c-431c-b029-0aeeae1f01d3.gif) [ ](https://user-images.githubusercontent.com/18114966/211141381-f006182e-fe2c-431c-b029-0aeeae1f01d3.gif)

:trollface:

**Comment by I-Got-You-Dead** [comment]
> harvest-yeahilif
> harvest-yeahilif
> > harvest-yeahilif

**Pull request merged**
