### PR TITLE
Add support for locate command on new versions from 1.18 to 1.20

### PR DESCRIPTION
**Pull request by gptlang**
## Description
Replace [mc_biome_java](https://github.com/SeedFinding/mc_biome_java) on versions greater than or equal to 1.18

## Related Issue
#316

## Motivation and Context
I want the locate command to work

## How Has This Been Tested?
Tested on MacOS, Windows, and Linux. Pretty much everything works.

It still works on older versions since we reuse old WorldGenUtils below 1.18.

## Screenshots (if appropriate):

image

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] My code follows the code style of this project.
- [x] Have you successfully ran tests with your changes locally?

### CODE REVIEW

**Comment by gptlang** [comment]
Converted to draft. Nether and end doesn't work... I totally forgot about dimensions. Only started playing minecraft. Haven't even beat the end yet

**Comment by gptlang** [comment]
Issues with dimension should be fixed.

**Comment by gptlang** [comment]
Tested on MacOS and Windows VM. It works. Should be fine to merge.

**Comment by gptlang** [comment]
I rebased and somehow that caused the CI to fail. 
```java
 /home/runner/work/meteor-rejects/meteor-rejects/src/main/java/anticope/rejects/modules/OreSim.java:215: error: chunk has private access in ChunkDataEvent
        doMathOnChunk(event.chunk);
```
OreSim.java isn't even changed. A bit confused

**Comment by RacoonDog** [comment]
> I rebased and somehow that caused the CI to fail.
> 
> ```java
>  /home/runner/work/meteor-rejects/meteor-rejects/src/main/java/anticope/rejects/modules/OreSim.java:215: error: chunk has private access in ChunkDataEvent
>         doMathOnChunk(event.chunk);
> ```
> 
> OreSim.java isn't even changed. A bit confused

`ChunkDataEvent` changed in meteor client, replace `event.chunk` with `event.chunk()`

**Comment by gptlang** [comment]
How about `returnChunkDataEvent` being private now?

**Comment by gptlang** [comment]
https://github.com/MeteorDevelopment/meteor-client/commit/484b2cf4eec460fd13d1eaee8555f24a05002bdc#diff-f53a8a16f50e8192d50e274b76fbc4276aad43b02fb784c06eb3fb75eb0286de

I'm guessing this means I can just delete the line

**Comment by RacoonDog** [comment]
> [MeteorDevelopment/meteor-client@484b2cf#diff-f53a8a16f50e8192d50e274b76fbc4276aad43b02fb784c06eb3fb75eb0286de](https://github.com/MeteorDevelopment/meteor-client/commit/484b2cf4eec460fd13d1eaee8555f24a05002bdc#diff-f53a8a16f50e8192d50e274b76fbc4276aad43b02fb784c06eb3fb75eb0286de)
> 
> I'm guessing this means I can just delete the line

yes

**Review by C10udburst — APPROVED** [review]

**Pull request merged**
