### PR TITLE
Some of my closed PRs

### PR DESCRIPTION
**Pull request by ThebestkillerTBK**
- `Load system fonts` - Disabling this for faster launch. You can put font into meteor-client/fonts folder. **requires restart to take effect**
- `Duplicate module names` - Allow duplicate module names. Best for addon compatibility.

### CODE REVIEW

**Comment by StormyBytes** [comment]
I don't like allowing duplicate module names. they were made like so in the client to allow addons to replace modules with their own.

**Comment by C10udburst** [comment]
> I don't like allowing duplicate module names. they were made like so in the client to allow addons to replace modules with their own.

+1

**Comment by I-Got-You-Dead** [comment]
What if some thing was added to the addon api for that reason 

> I don't like allowing duplicate module names. they were made like so in the client to allow addons to replace modules with their own.

**Comment by I-Got-You-Dead** [comment]
Just a simple boolean to override  or not

**Review by C10udburst — APPROVED** [review]

**Pull request merged**
