### PR TITLE
small improvements to chatbot

### PR DESCRIPTION
**Pull request by Wide-Cat**
Just small stuff. Also, it might be a good idea to expand the commands system to not rely fully on starscript because otherwise it would be difficult to add new commands with functionality beyond what starscript provides - e.g. '!bestping/!worstping'

### CODE REVIEW

**Comment by C10udburst** [comment]
Hmm.. I don't really see the use case for this, as you can already edit the commands to include any characters, including <kbd>\></kbd>.

**Comment by C10udburst** [comment]
> Just small stuff. Also, it might be a good idea to expand the commands system to not rely fully on starscript because otherwise it would be difficult to add new commands with functionality beyond what starscript provides - e.g. '!bestping/!worstping'

yeah, the module is kinda limited, but I don't think that starscript itself is the most limiting factor here. I think that relying on the [`MeteorStarscript`](https://github.com/MeteorDevelopment/meteor-client/blob/master/src/main/java/meteordevelopment/meteorclient/utils/misc/MeteorStarscript.java) class is what limits this module the most.

**Comment by Wide-Cat** [comment]
mmm thats a good point, I kinda want to add some new commands to the module but I'm just not sure on the best way to accomplish it, maybe a rejects starscript file if i can figure it out

**Comment by Wide-Cat** [comment]
in the meantime ill close this bc you were right in your first comment

**Pull request closed without merging**
